export enum SCALE {
  MAJOR = 'MAJOR',
  MINOR = 'MINOR',
  DORIAN = 'DORIAN',
  MIXOLYDIAN = 'MIXOLYDIAN',
  LYDIAN = 'LYDIAN',
  PHRYGIAN = 'PHRYGIAN',
  LOCRIAN = 'LOCRIAN',
  HARMONIC_MINOR = 'HARMONIC_MINOR',
  HARMONIC_MAJOR = 'HARMONIC_MAJOR',
  DORIAN_NR_4 = 'DORIAN_NR_4',
  PHRYGIAN_DOMINANT = 'PHRYGIAN_DOMINANT',
  MELODIC_MINOR = 'MELODIC_MINOR',
  LYDIAN_AUGMENTED = 'LYDIAN_AUGMENTED',
  LYDIAN_DOMINANT = 'LYDIAN_DOMINANT',
  HUNGARIAN_MINOR = 'HUNGARIAN_MINOR',
  SUPER_LOCRIAN = 'SUPER_LOCRIAN',
  SPANISH = 'SPANISH',
  BHAIRAV = 'BHAIRAV',
}

export type ScaleDef = {
  [k in SCALE]: [number, number, number, number, number, number, number];
};

export const SCALES: ScaleDef = {
  [SCALE.MAJOR]: [0, 2, 4, 5, 7, 9, 11],
  [SCALE.MINOR]: [0, 2, 3, 5, 7, 8, 10],
  [SCALE.DORIAN]: [0, 2, 3, 5, 7, 9, 10],
  [SCALE.MIXOLYDIAN]: [0, 2, 4, 5, 7, 9, 10],
  [SCALE.LYDIAN]: [0, 2, 4, 6, 7, 9, 11],
  [SCALE.PHRYGIAN]: [0, 1, 3, 5, 7, 8, 10],
  [SCALE.LOCRIAN]: [0, 1, 3, 5, 6, 8, 10],
  [SCALE.HARMONIC_MINOR]: [0, 2, 3, 5, 7, 8, 11],
  [SCALE.HARMONIC_MAJOR]: [0, 2, 4, 5, 7, 8, 11],
  [SCALE.DORIAN_NR_4]: [0, 2, 3, 6, 7, 9, 10],
  [SCALE.PHRYGIAN_DOMINANT]: [0, 1, 4, 5, 7, 8, 10],
  [SCALE.MELODIC_MINOR]: [0, 2, 3, 5, 7, 9, 11],
  [SCALE.LYDIAN_AUGMENTED]: [0, 2, 4, 6, 8, 9, 11],
  [SCALE.LYDIAN_DOMINANT]: [0, 2, 4, 6, 7, 9, 10],
  [SCALE.HUNGARIAN_MINOR]: [0, 2, 3, 6, 7, 8, 11],
  [SCALE.SUPER_LOCRIAN]: [0, 1, 3, 4, 6, 8, 10],
  [SCALE.SPANISH]: [0, 1, 4, 5, 7, 9, 10],
  [SCALE.BHAIRAV]: [0, 1, 4, 5, 7, 8, 11],
};

export const DEFAUL_SCALE = SCALES[SCALE.PHRYGIAN];
